### ISSUE TITLE
吐槽下CPE的问题

### ISSUE THREAD

**Issue by junmoxiao** [yaklang/yaklang.github.io#3]
```
甚至于说我之前面过很多候选人，在问到你知道“CPE”是什么吗？很多人答不出来
```

这CPE又不是什么公认的权威技术名词缩写，做技术的答不出来很正常，你直接说指纹识别别人不就知道了。

**Comment by VillanCh** [comment]
当然不是说没听过 CPE 就会认为不懂指纹识别

**Comment by VillanCh** [comment]
其实这句话并不是在否定候选人的努力，更多是想表达 “充分调研，了解行业”，避免重复造轮子这类问题，可能措辞确实有点激进

**Comment by junmoxiao** [comment]
嗯

**Comment by VillanCh** [comment]
感谢你的意见，会仔细斟酌一下文内的用词或者一些说法 🙏 十分感谢
